// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.18408
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace MercaderSG.My.Resources
{

    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    /// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("MercaderSG.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AC
        {
            get
            {
                var obj = ResourceManager.GetObject("AC", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap accept
        {
            get
            {
                var obj = ResourceManager.GetObject("accept", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap add
        {
            get
            {
                var obj = ResourceManager.GetObject("add", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AdvertenciaE32
        {
            get
            {
                var obj = ResourceManager.GetObject("AdvertenciaE32", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AnteriorE
        {
            get
            {
                var obj = ResourceManager.GetObject("AnteriorE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ar
        {
            get
            {
                var obj = ResourceManager.GetObject("ar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BitacoraE
        {
            get
            {
                var obj = ResourceManager.GetObject("BitacoraE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BuscarE
        {
            get
            {
                var obj = ResourceManager.GetObject("BuscarE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Calcular
        {
            get
            {
                var obj = ResourceManager.GetObject("Calcular", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CambiarPassE
        {
            get
            {
                var obj = ResourceManager.GetObject("CambiarPassE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CancelBtn
        {
            get
            {
                var obj = ResourceManager.GetObject("CancelBtn", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Clear
        {
            get
            {
                var obj = ResourceManager.GetObject("Clear", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ClienteE
        {
            get
            {
                var obj = ResourceManager.GetObject("ClienteE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap database_save
        {
            get
            {
                var obj = ResourceManager.GetObject("database_save", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap delete
        {
            get
            {
                var obj = ResourceManager.GetObject("delete", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap DesbloImg
        {
            get
            {
                var obj = ResourceManager.GetObject("DesbloImg", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap DesbloquearG
        {
            get
            {
                var obj = ResourceManager.GetObject("DesbloquearG", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ExcelE
        {
            get
            {
                var obj = ResourceManager.GetObject("ExcelE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap FamiliaE
        {
            get
            {
                var obj = ResourceManager.GetObject("FamiliaE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap folder_database
        {
            get
            {
                var obj = ResourceManager.GetObject("folder_database", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap GestionNV
        {
            get
            {
                var obj = ResourceManager.GetObject("GestionNV", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap group_user
        {
            get
            {
                var obj = ResourceManager.GetObject("group_user", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap IdiomaE
        {
            get
            {
                var obj = ResourceManager.GetObject("IdiomaE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap IdiomaE1
        {
            get
            {
                var obj = ResourceManager.GetObject("IdiomaE1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap InfoDocE
        {
            get
            {
                var obj = ResourceManager.GetObject("InfoDocE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap InformationE32
        {
            get
            {
                var obj = ResourceManager.GetObject("InformationE32", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap LogInE
        {
            get
            {
                var obj = ResourceManager.GetObject("LogInE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap MasOpcionesE
        {
            get
            {
                var obj = ResourceManager.GetObject("MasOpcionesE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap newPage
        {
            get
            {
                var obj = ResourceManager.GetObject("newPage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap NoPatentes
        {
            get
            {
                var obj = ResourceManager.GetObject("NoPatentes", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap NoPatentes1
        {
            get
            {
                var obj = ResourceManager.GetObject("NoPatentes1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap NotaE
        {
            get
            {
                var obj = ResourceManager.GetObject("NotaE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap package
        {
            get
            {
                var obj = ResourceManager.GetObject("package", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap page
        {
            get
            {
                var obj = ResourceManager.GetObject("page", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap page_add
        {
            get
            {
                var obj = ResourceManager.GetObject("page_add", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap page_green
        {
            get
            {
                var obj = ResourceManager.GetObject("page_green", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap pencil
        {
            get
            {
                var obj = ResourceManager.GetObject("pencil", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Permisos
        {
            get
            {
                var obj = ResourceManager.GetObject("Permisos", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap phone_delete
        {
            get
            {
                var obj = ResourceManager.GetObject("phone_delete", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap PrecioE
        {
            get
            {
                var obj = ResourceManager.GetObject("PrecioE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap PrimeroE
        {
            get
            {
                var obj = ResourceManager.GetObject("PrimeroE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ProveedorE
        {
            get
            {
                var obj = ResourceManager.GetObject("ProveedorE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RecargarE
        {
            get
            {
                var obj = ResourceManager.GetObject("RecargarE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Resetear48
        {
            get
            {
                var obj = ResourceManager.GetObject("Resetear48", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ResetearPass
        {
            get
            {
                var obj = ResourceManager.GetObject("ResetearPass", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RestoreE
        {
            get
            {
                var obj = ResourceManager.GetObject("RestoreE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap RestoreE1
        {
            get
            {
                var obj = ResourceManager.GetObject("RestoreE1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SalirE
        {
            get
            {
                var obj = ResourceManager.GetObject("SalirE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap search
        {
            get
            {
                var obj = ResourceManager.GetObject("search", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SiguienteE
        {
            get
            {
                var obj = ResourceManager.GetObject("SiguienteE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap StockE
        {
            get
            {
                var obj = ResourceManager.GetObject("StockE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UltimoE
        {
            get
            {
                var obj = ResourceManager.GetObject("UltimoE", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap us
        {
            get
            {
                var obj = ResourceManager.GetObject("us", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}