// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.18051
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace Datos.My.Resources
{

    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    /// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class ArchivoIdioma
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchivoIdioma() : base()
        {
        }

        /// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Datos.ArchivoIdioma", typeof(ArchivoIdioma).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El cliente esta dado de baja.
        /// </summary>
        internal static string ClienteDadoBaja
        {
            get
            {
                return ResourceManager.GetString("ClienteDadoBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El cliente ya esta dado de baja.
        /// </summary>
        internal static string ClienteEstaEliminado
        {
            get
            {
                return ResourceManager.GetString("ClienteEstaEliminado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string CMBApellido
        {
            get
            {
                return ResourceManager.GetString("CMBApellido", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a CUIT.
        /// </summary>
        internal static string CMBCuit
        {
            get
            {
                return ResourceManager.GetString("CMBCuit", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string CMBNombre
        {
            get
            {
                return ResourceManager.GetString("CMBNombre", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Razón Social.
        /// </summary>
        internal static string CMBRazonSocial
        {
            get
            {
                return ResourceManager.GetString("CMBRazonSocial", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Sector.
        /// </summary>
        internal static string CMBSector
        {
            get
            {
                return ResourceManager.GetString("CMBSector", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string CMBUsuario
        {
            get
            {
                return ResourceManager.GetString("CMBUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Mensaje: .
        /// </summary>
        internal static string DescErrorMensaje
        {
            get
            {
                return ResourceManager.GetString("DescErrorMensaje", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a No se puede abrir la base de datos solicitada por el inicio de sesión. Error de inicio de sesión.
        /// </summary>
        internal static string Error4060
        {
            get
            {
                return ResourceManager.GetString("Error4060", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La base de datos no existe.
        /// </summary>
        internal static string Error911
        {
            get
            {
                return ResourceManager.GetString("Error911", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Error al generar el respaldo. El archivo es multivolumen y no se agregaron todas las partes.
        /// </summary>
        internal static string ErrorRestore3132
        {
            get
            {
                return ResourceManager.GetString("ErrorRestore3132", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La familia no existe.
        /// </summary>
        internal static string FamiliaDadaBaja
        {
            get
            {
                return ResourceManager.GetString("FamiliaDadaBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a No existen usuarios registrados en la base de datos.
        /// </summary>
        internal static string NoExistenUsuariosBD
        {
            get
            {
                return ResourceManager.GetString("NoExistenUsuariosBD", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El nombre del producto ya existe. Vuelva a ingresar otro.
        /// </summary>
        internal static string NombreProductoExistente
        {
            get
            {
                return ResourceManager.GetString("NombreProductoExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de pedido esta dada de baja.
        /// </summary>
        internal static string NotaPedidoDadaBaja
        {
            get
            {
                return ResourceManager.GetString("NotaPedidoDadaBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de pedido no existe.
        /// </summary>
        internal static string NotaPedidoNoExiste
        {
            get
            {
                return ResourceManager.GetString("NotaPedidoNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de venta esta dada de baja.
        /// </summary>
        internal static string NotaVentaDadaBaja
        {
            get
            {
                return ResourceManager.GetString("NotaVentaDadaBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de venta no existe.
        /// </summary>
        internal static string NotaVentaNoExiste
        {
            get
            {
                return ResourceManager.GetString("NotaVentaNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Error: .
        /// </summary>
        internal static string NroErrorMensaje
        {
            get
            {
                return ResourceManager.GetString("NroErrorMensaje", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El número de teléfono no existe.
        /// </summary>
        internal static string NumeroTelefonoNoExiste
        {
            get
            {
                return ResourceManager.GetString("NumeroTelefonoNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El producto esta dado de baja.
        /// </summary>
        internal static string ProductoDadoBaja
        {
            get
            {
                return ResourceManager.GetString("ProductoDadoBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El producto ya esta dado de baja.
        /// </summary>
        internal static string ProductoEstaEliminado
        {
            get
            {
                return ResourceManager.GetString("ProductoEstaEliminado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El proveedor esta dado de baja.
        /// </summary>
        internal static string ProveedorDadoBaja
        {
            get
            {
                return ResourceManager.GetString("ProveedorDadoBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El proveedor ya esta dado de baja.
        /// </summary>
        internal static string ProveedorEstaEliminado
        {
            get
            {
                return ResourceManager.GetString("ProveedorEstaEliminado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario esta bloqueado, contacte con la persona adecuada para desbloquear usuarios.
        /// </summary>
        internal static string UsuarioBloqueado
        {
            get
            {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario esta dado de baja.
        /// </summary>
        internal static string UsuarioDadoBaja
        {
            get
            {
                return ResourceManager.GetString("UsuarioDadoBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario ya esta dado de baja.
        /// </summary>
        internal static string UsuarioEstaEliminado
        {
            get
            {
                return ResourceManager.GetString("UsuarioEstaEliminado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario no esta bloqueado.
        /// </summary>
        internal static string UsuarioNoBloqueado
        {
            get
            {
                return ResourceManager.GetString("UsuarioNoBloqueado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario no existe. Vuelva a ingresar otro.
        /// </summary>
        internal static string UsuarioNoExiste
        {
            get
            {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
    }
}