'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18051
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ArchivoIdioma
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Datos.ArchivoIdioma", GetType(ArchivoIdioma).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El cliente esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ClienteDadoBaja() As String
            Get
                Return ResourceManager.GetString("ClienteDadoBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El cliente ya esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ClienteEstaEliminado() As String
            Get
                Return ResourceManager.GetString("ClienteEstaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellido.
        '''</summary>
        Friend Shared ReadOnly Property CMBApellido() As String
            Get
                Return ResourceManager.GetString("CMBApellido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUIT.
        '''</summary>
        Friend Shared ReadOnly Property CMBCuit() As String
            Get
                Return ResourceManager.GetString("CMBCuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property CMBNombre() As String
            Get
                Return ResourceManager.GetString("CMBNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Razón Social.
        '''</summary>
        Friend Shared ReadOnly Property CMBRazonSocial() As String
            Get
                Return ResourceManager.GetString("CMBRazonSocial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sector.
        '''</summary>
        Friend Shared ReadOnly Property CMBSector() As String
            Get
                Return ResourceManager.GetString("CMBSector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario.
        '''</summary>
        Friend Shared ReadOnly Property CMBUsuario() As String
            Get
                Return ResourceManager.GetString("CMBUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mensaje: .
        '''</summary>
        Friend Shared ReadOnly Property DescErrorMensaje() As String
            Get
                Return ResourceManager.GetString("DescErrorMensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede abrir la base de datos solicitada por el inicio de sesión. Error de inicio de sesión.
        '''</summary>
        Friend Shared ReadOnly Property Error4060() As String
            Get
                Return ResourceManager.GetString("Error4060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La base de datos no existe.
        '''</summary>
        Friend Shared ReadOnly Property Error911() As String
            Get
                Return ResourceManager.GetString("Error911", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al generar el respaldo. El archivo es multivolumen y no se agregaron todas las partes.
        '''</summary>
        Friend Shared ReadOnly Property ErrorRestore3132() As String
            Get
                Return ResourceManager.GetString("ErrorRestore3132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La familia no existe.
        '''</summary>
        Friend Shared ReadOnly Property FamiliaDadaBaja() As String
            Get
                Return ResourceManager.GetString("FamiliaDadaBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No existen usuarios registrados en la base de datos.
        '''</summary>
        Friend Shared ReadOnly Property NoExistenUsuariosBD() As String
            Get
                Return ResourceManager.GetString("NoExistenUsuariosBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El nombre del producto ya existe. Vuelva a ingresar otro.
        '''</summary>
        Friend Shared ReadOnly Property NombreProductoExistente() As String
            Get
                Return ResourceManager.GetString("NombreProductoExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de pedido esta dada de baja.
        '''</summary>
        Friend Shared ReadOnly Property NotaPedidoDadaBaja() As String
            Get
                Return ResourceManager.GetString("NotaPedidoDadaBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de pedido no existe.
        '''</summary>
        Friend Shared ReadOnly Property NotaPedidoNoExiste() As String
            Get
                Return ResourceManager.GetString("NotaPedidoNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de venta esta dada de baja.
        '''</summary>
        Friend Shared ReadOnly Property NotaVentaDadaBaja() As String
            Get
                Return ResourceManager.GetString("NotaVentaDadaBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de venta no existe.
        '''</summary>
        Friend Shared ReadOnly Property NotaVentaNoExiste() As String
            Get
                Return ResourceManager.GetString("NotaVentaNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error: .
        '''</summary>
        Friend Shared ReadOnly Property NroErrorMensaje() As String
            Get
                Return ResourceManager.GetString("NroErrorMensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El número de teléfono no existe.
        '''</summary>
        Friend Shared ReadOnly Property NumeroTelefonoNoExiste() As String
            Get
                Return ResourceManager.GetString("NumeroTelefonoNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El producto esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ProductoDadoBaja() As String
            Get
                Return ResourceManager.GetString("ProductoDadoBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El producto ya esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ProductoEstaEliminado() As String
            Get
                Return ResourceManager.GetString("ProductoEstaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El proveedor esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ProveedorDadoBaja() As String
            Get
                Return ResourceManager.GetString("ProveedorDadoBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El proveedor ya esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property ProveedorEstaEliminado() As String
            Get
                Return ResourceManager.GetString("ProveedorEstaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario esta bloqueado, contacte con la persona adecuada para desbloquear usuarios.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioBloqueado() As String
            Get
                Return ResourceManager.GetString("UsuarioBloqueado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioDadoBaja() As String
            Get
                Return ResourceManager.GetString("UsuarioDadoBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario ya esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioEstaEliminado() As String
            Get
                Return ResourceManager.GetString("UsuarioEstaEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario no esta bloqueado.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioNoBloqueado() As String
            Get
                Return ResourceManager.GetString("UsuarioNoBloqueado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario no existe. Vuelva a ingresar otro.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioNoExiste() As String
            Get
                Return ResourceManager.GetString("UsuarioNoExiste", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
