// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.18051
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace Negocios.My.Resources
{

    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    /// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class ArchivoIdioma
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchivoIdioma() : base()
        {
        }

        /// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Negocios.ArchivoIdioma", typeof(ArchivoIdioma).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta del cliente se realizo correctamente.
        /// </summary>
        internal static string AltaCliente
        {
            get
            {
                return ResourceManager.GetString("AltaCliente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta de la familia se realizo correctamente.
        /// </summary>
        internal static string AltaFamilia
        {
            get
            {
                return ResourceManager.GetString("AltaFamilia", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta de la localidad se realizo correctamente.
        /// </summary>
        internal static string AltaLocalidad
        {
            get
            {
                return ResourceManager.GetString("AltaLocalidad", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de pedido fue creada satisfactoriamente.
        /// </summary>
        internal static string AltaNotaPedido
        {
            get
            {
                return ResourceManager.GetString("AltaNotaPedido", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de venta fue creada satisfactoriamente.
        /// </summary>
        internal static string AltaNotaVenta
        {
            get
            {
                return ResourceManager.GetString("AltaNotaVenta", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El precio del producto se actualizo correctamente.
        /// </summary>
        internal static string AltaPrecio
        {
            get
            {
                return ResourceManager.GetString("AltaPrecio", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta del producto se realizo correctamente.
        /// </summary>
        internal static string AltaProducto
        {
            get
            {
                return ResourceManager.GetString("AltaProducto", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta del proveedor se realizo correctamente.
        /// </summary>
        internal static string AltaProveedor
        {
            get
            {
                return ResourceManager.GetString("AltaProveedor", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El stock del producto ha sido actualizado correctamente.
        /// </summary>
        internal static string AltaStock
        {
            get
            {
                return ResourceManager.GetString("AltaStock", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El alta del usuario se realizo correctamente.
        /// </summary>
        internal static string AltaUsuario
        {
            get
            {
                return ResourceManager.GetString("AltaUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja del cliente se realizo correctamente.
        /// </summary>
        internal static string BajaCliente
        {
            get
            {
                return ResourceManager.GetString("BajaCliente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja de la familia se realizo correctamente.
        /// </summary>
        internal static string BajaFamilia
        {
            get
            {
                return ResourceManager.GetString("BajaFamilia", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja de la nota de venta se realizo correctamente.
        /// </summary>
        internal static string BajaNotaVenta
        {
            get
            {
                return ResourceManager.GetString("BajaNotaVenta", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja del producto se realizo correctamente.
        /// </summary>
        internal static string BajaProducto
        {
            get
            {
                return ResourceManager.GetString("BajaProducto", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja del proveedor se realizo correctamente.
        /// </summary>
        internal static string BajaProveedor
        {
            get
            {
                return ResourceManager.GetString("BajaProveedor", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La baja del usuario se realizo correctamente.
        /// </summary>
        internal static string BajaUsuario
        {
            get
            {
                return ResourceManager.GetString("BajaUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El cliente que desea dar de alta ya existe.
        /// </summary>
        internal static string ClienteExistente
        {
            get
            {
                return ResourceManager.GetString("ClienteExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a CUIT.
        /// </summary>
        internal static string CMBCuit
        {
            get
            {
                return ResourceManager.GetString("CMBCuit", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string CMBNombre
        {
            get
            {
                return ResourceManager.GetString("CMBNombre", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string CMBUsuario
        {
            get
            {
                return ResourceManager.GetString("CMBUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La contraseña fue cambiada correctamente.
        /// </summary>
        internal static string ContraseñaCambiada
        {
            get
            {
                return ResourceManager.GetString("ContraseñaCambiada", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La contraseña es invalida.
        /// </summary>
        internal static string ContraseñaInvalida
        {
            get
            {
                return ResourceManager.GetString("ContraseñaInvalida", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Se depuró correctamente la Bitácora.
        /// </summary>
        internal static string DepurarBitacora
        {
            get
            {
                return ResourceManager.GetString("DepurarBitacora", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario ha sido desbloqueado correctamente.
        /// </summary>
        internal static string DesbloquearUsuario
        {
            get
            {
                return ResourceManager.GetString("DesbloquearUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El número de teléfono se elimino correctamente.
        /// </summary>
        internal static string EliminarTelefono
        {
            get
            {
                return ResourceManager.GetString("EliminarTelefono", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La familia que desea dar de alta ya existe.
        /// </summary>
        internal static string FamiliaExistente
        {
            get
            {
                return ResourceManager.GetString("FamiliaExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La familia no existe.
        /// </summary>
        internal static string FamiliaInexistente
        {
            get
            {
                return ResourceManager.GetString("FamiliaInexistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La localidad que desea dar de alta ya existe.
        /// </summary>
        internal static string LocalidadExistente
        {
            get
            {
                return ResourceManager.GetString("LocalidadExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Los datos del cliente se actualizaron correctamente.
        /// </summary>
        internal static string ModificarCliente
        {
            get
            {
                return ResourceManager.GetString("ModificarCliente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Los datos de la familia se actualizaron correctamente.
        /// </summary>
        internal static string ModificarFamilia
        {
            get
            {
                return ResourceManager.GetString("ModificarFamilia", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Los datos del producto se actualizaron correctamente.
        /// </summary>
        internal static string ModificarProducto
        {
            get
            {
                return ResourceManager.GetString("ModificarProducto", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Los datos del proveedor se actualizaron correctamente.
        /// </summary>
        internal static string ModificarProveedor
        {
            get
            {
                return ResourceManager.GetString("ModificarProveedor", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Los datos del usuario se actualizaron correctamente.
        /// </summary>
        internal static string ModificarUsuario
        {
            get
            {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de pedido no existe.
        /// </summary>
        internal static string NotaPedidoNoExiste
        {
            get
            {
                return ResourceManager.GetString("NotaPedidoNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La nota de venta no existe.
        /// </summary>
        internal static string NotaVentaNoExiste
        {
            get
            {
                return ResourceManager.GetString("NotaVentaNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a No se puede eliminar la familia.
        /// CAUSA: U.F.C.C.P.
        /// </summary>
        internal static string PrivilegiosFamilia
        {
            get
            {
                return ResourceManager.GetString("PrivilegiosFamilia", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a No se puede dar de baja el usuario. CAUSA: U.U.C.C.P.
        /// </summary>
        internal static string PrivilegiosUsuario
        {
            get
            {
                return ResourceManager.GetString("PrivilegiosUsuario", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El producto que desea dar de alta ya existe.
        /// </summary>
        internal static string ProductoExistente
        {
            get
            {
                return ResourceManager.GetString("ProductoExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El proveedor que desea dar de alta ya existe.
        /// </summary>
        internal static string ProveedorExistente
        {
            get
            {
                return ResourceManager.GetString("ProveedorExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a No existe un remito para esa nota de venta.
        /// </summary>
        internal static string RemitoNoExiste
        {
            get
            {
                return ResourceManager.GetString("RemitoNoExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a Esta nota de venta ya posee un remito generado.
        /// </summary>
        internal static string RemitoNVExiste
        {
            get
            {
                return ResourceManager.GetString("RemitoNVExiste", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El remito ha sido generado correctamente.
        /// </summary>
        internal static string RemitoNVGenerado
        {
            get
            {
                return ResourceManager.GetString("RemitoNVGenerado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a La contraseña ha sido cambiada correctamente.
        /// </summary>
        internal static string ResetContrasena
        {
            get
            {
                return ResourceManager.GetString("ResetContrasena", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario ha sido bloqueado por el sistema. Contacte con el usuario correspondiente para desbloquear el usuario.
        /// </summary>
        internal static string UsuarioBloqueado
        {
            get
            {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario esta dado de baja.
        /// </summary>
        internal static string UsuarioDadoBaja
        {
            get
            {
                return ResourceManager.GetString("UsuarioDadoBaja", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario que desea dar de alta ya existe.
        /// </summary>
        internal static string UsuarioExistente
        {
            get
            {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario no existe.
        /// </summary>
        internal static string UsuarioInexistente
        {
            get
            {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a El usuario no puede ser bloqueado. CAUSA: U.U.C.C.P.
        /// </summary>
        internal static string UsuarioRevision
        {
            get
            {
                return ResourceManager.GetString("UsuarioRevision", resourceCulture);
            }
        }
    }
}