'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18051
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ArchivoIdioma
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Negocios.ArchivoIdioma", GetType(ArchivoIdioma).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta del cliente se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaCliente() As String
            Get
                Return ResourceManager.GetString("AltaCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta de la familia se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaFamilia() As String
            Get
                Return ResourceManager.GetString("AltaFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta de la localidad se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaLocalidad() As String
            Get
                Return ResourceManager.GetString("AltaLocalidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de pedido fue creada satisfactoriamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaNotaPedido() As String
            Get
                Return ResourceManager.GetString("AltaNotaPedido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de venta fue creada satisfactoriamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaNotaVenta() As String
            Get
                Return ResourceManager.GetString("AltaNotaVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El precio del producto se actualizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaPrecio() As String
            Get
                Return ResourceManager.GetString("AltaPrecio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta del producto se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaProducto() As String
            Get
                Return ResourceManager.GetString("AltaProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta del proveedor se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaProveedor() As String
            Get
                Return ResourceManager.GetString("AltaProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El stock del producto ha sido actualizado correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaStock() As String
            Get
                Return ResourceManager.GetString("AltaStock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El alta del usuario se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property AltaUsuario() As String
            Get
                Return ResourceManager.GetString("AltaUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja del cliente se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaCliente() As String
            Get
                Return ResourceManager.GetString("BajaCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja de la familia se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaFamilia() As String
            Get
                Return ResourceManager.GetString("BajaFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja de la nota de venta se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaNotaVenta() As String
            Get
                Return ResourceManager.GetString("BajaNotaVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja del producto se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaProducto() As String
            Get
                Return ResourceManager.GetString("BajaProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja del proveedor se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaProveedor() As String
            Get
                Return ResourceManager.GetString("BajaProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La baja del usuario se realizo correctamente.
        '''</summary>
        Friend Shared ReadOnly Property BajaUsuario() As String
            Get
                Return ResourceManager.GetString("BajaUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El cliente que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property ClienteExistente() As String
            Get
                Return ResourceManager.GetString("ClienteExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUIT.
        '''</summary>
        Friend Shared ReadOnly Property CMBCuit() As String
            Get
                Return ResourceManager.GetString("CMBCuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property CMBNombre() As String
            Get
                Return ResourceManager.GetString("CMBNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario.
        '''</summary>
        Friend Shared ReadOnly Property CMBUsuario() As String
            Get
                Return ResourceManager.GetString("CMBUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La contraseña fue cambiada correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ContraseñaCambiada() As String
            Get
                Return ResourceManager.GetString("ContraseñaCambiada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La contraseña es invalida.
        '''</summary>
        Friend Shared ReadOnly Property ContraseñaInvalida() As String
            Get
                Return ResourceManager.GetString("ContraseñaInvalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se depuró correctamente la Bitácora.
        '''</summary>
        Friend Shared ReadOnly Property DepurarBitacora() As String
            Get
                Return ResourceManager.GetString("DepurarBitacora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario ha sido desbloqueado correctamente.
        '''</summary>
        Friend Shared ReadOnly Property DesbloquearUsuario() As String
            Get
                Return ResourceManager.GetString("DesbloquearUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El número de teléfono se elimino correctamente.
        '''</summary>
        Friend Shared ReadOnly Property EliminarTelefono() As String
            Get
                Return ResourceManager.GetString("EliminarTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La familia que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property FamiliaExistente() As String
            Get
                Return ResourceManager.GetString("FamiliaExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La familia no existe.
        '''</summary>
        Friend Shared ReadOnly Property FamiliaInexistente() As String
            Get
                Return ResourceManager.GetString("FamiliaInexistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La localidad que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property LocalidadExistente() As String
            Get
                Return ResourceManager.GetString("LocalidadExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos del cliente se actualizaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ModificarCliente() As String
            Get
                Return ResourceManager.GetString("ModificarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos de la familia se actualizaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ModificarFamilia() As String
            Get
                Return ResourceManager.GetString("ModificarFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos del producto se actualizaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ModificarProducto() As String
            Get
                Return ResourceManager.GetString("ModificarProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos del proveedor se actualizaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ModificarProveedor() As String
            Get
                Return ResourceManager.GetString("ModificarProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos del usuario se actualizaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ModificarUsuario() As String
            Get
                Return ResourceManager.GetString("ModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de pedido no existe.
        '''</summary>
        Friend Shared ReadOnly Property NotaPedidoNoExiste() As String
            Get
                Return ResourceManager.GetString("NotaPedidoNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La nota de venta no existe.
        '''</summary>
        Friend Shared ReadOnly Property NotaVentaNoExiste() As String
            Get
                Return ResourceManager.GetString("NotaVentaNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede eliminar la familia.
        '''CAUSA: U.F.C.C.P.
        '''</summary>
        Friend Shared ReadOnly Property PrivilegiosFamilia() As String
            Get
                Return ResourceManager.GetString("PrivilegiosFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede dar de baja el usuario. CAUSA: U.U.C.C.P.
        '''</summary>
        Friend Shared ReadOnly Property PrivilegiosUsuario() As String
            Get
                Return ResourceManager.GetString("PrivilegiosUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El producto que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property ProductoExistente() As String
            Get
                Return ResourceManager.GetString("ProductoExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El proveedor que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property ProveedorExistente() As String
            Get
                Return ResourceManager.GetString("ProveedorExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No existe un remito para esa nota de venta.
        '''</summary>
        Friend Shared ReadOnly Property RemitoNoExiste() As String
            Get
                Return ResourceManager.GetString("RemitoNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esta nota de venta ya posee un remito generado.
        '''</summary>
        Friend Shared ReadOnly Property RemitoNVExiste() As String
            Get
                Return ResourceManager.GetString("RemitoNVExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El remito ha sido generado correctamente.
        '''</summary>
        Friend Shared ReadOnly Property RemitoNVGenerado() As String
            Get
                Return ResourceManager.GetString("RemitoNVGenerado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La contraseña ha sido cambiada correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ResetContrasena() As String
            Get
                Return ResourceManager.GetString("ResetContrasena", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario ha sido bloqueado por el sistema. Contacte con el usuario correspondiente para desbloquear el usuario.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioBloqueado() As String
            Get
                Return ResourceManager.GetString("UsuarioBloqueado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario esta dado de baja.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioDadoBaja() As String
            Get
                Return ResourceManager.GetString("UsuarioDadoBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario que desea dar de alta ya existe.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioExistente() As String
            Get
                Return ResourceManager.GetString("UsuarioExistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario no existe.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioInexistente() As String
            Get
                Return ResourceManager.GetString("UsuarioInexistente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El usuario no puede ser bloqueado. CAUSA: U.U.C.C.P.
        '''</summary>
        Friend Shared ReadOnly Property UsuarioRevision() As String
            Get
                Return ResourceManager.GetString("UsuarioRevision", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
